apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: example-host
  namespace: ambassador
spec:
  hostname: demo-api-gateway.example.com
  acmeProvider:
    authority: none
  tlsSecret:
    name: ambassador-certs
