---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-api-gateway.example.com
  # cert-manager will put the resulting Secret in the same Kubernetes
  # namespace as the Certificate. You should create the certificate in
  # whichever namespace you want to configure a Host.
  namespace: ambassador
spec:
  secretName: ambassador-certs
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  commonName: demo-api-gateway.example.com
  dnsNames:
  - demo-api-gateway.example.com
